sonar.projectKey=JIveth-14_Pulperia_SoftwareII
sonar.projectName=Pulperia_SoftwareII
sonar.organization=jiveth-14
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

sonar.sources=src,MORA_APP/backend,MORA_APP/frontend
sonar.tests=__tests__,src,MORA_APP/__tests__
sonar.test.inclusions=__tests__/**,src/**/__tests__/**,src/app/api/**/*.test.ts,MORA_APP/__tests__/**,MORA_APP/**/__tests__/**
sonar.sourceEncoding=UTF-8

sonar.exclusions=src/lib/supabase/sql/**,MORA_APP/docs/**,**/node_modules/**,**/coverage/**,**/*.test.js,**/*.test.ts,**/*.test.jsx,**/*.test.tsx,**/dist/**,**/build/**,.next/**,legacy/**
sonar.coverage.exclusions=src/lib/supabase/sql/**,**/node_modules/**,**/*.test.js,**/*.test.ts,**/*.test.jsx,**/*.test.tsx,**/__tests__/**,legacy/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

sonar.qualitygate.wait=false
sonar.cpd.exclusions=**/*test.ts,**/*test.tsx,**/__tests__/**,legacy/**
