sonar.projectKey=JIveth-14_Pulperia_SoftwareII
sonar.projectName=Pulperia_SoftwareII
sonar.organization=jiveth-14
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

sonar.sources=src
sonar.tests=__tests__
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.test.ts,**/*.test.jsx,**/*.test.tsx,**/dist/**,**/build/**,.next/**
sonar.coverage.exclusions=**/node_modules/**,**/*.test.js,**/*.test.ts,**/*.test.jsx,**/*.test.tsx,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

sonar.qualitygate.wait=true
sonar.cpd.exclusions=**/*test.ts,**/*test.tsx,**/__tests__/**
